name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install gcc and nasm
        run: sudo apt-get install -y gcc nasm

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      

      - name: Install dependencies
        run: pipenv install

      - name: Run tests
        run: pipenv run python -m pytest --no-header -v -W ignore::DeprecationWarning
